import { Artist } from './models';

export const ARTISTS: Artist[] = [
  {
    id: '1',
    name: 'The Beatles',
    bio: 'The Beatles were an English rock band formed in Liverpool in 1960. With a line-up comprising John Lennon, Paul McCartney, George Harrison and Ringo Starr, they are regarded as the most influential band of all time.',
    imageUrl: 'assets/images/the-beatles.jpg',
    albums: [
      {
        id: '1',
        title: 'Please Please Me',
        year: 1963,
        imageUrl: 'assets/images/please-please-me.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 5,
        rare: true,
      },
      {
        id: '2',
        title: 'With the Beatles',
        year: 1963,
        imageUrl: 'assets/images/with-the-beatles.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 4,
        rare: false,
      },
      {
        id: '3',
        title: "A Hard Day's Night",
        year: 1964,
        imageUrl: 'assets/images/a-hard-days-night.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 10,
        rare: false,
      },
      {
        id: '4',
        title: 'Beatles for Sale',
        year: 1964,
        imageUrl: 'assets/images/beatles-for-sale.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 23,
        rare: false,
      },
      {
        id: '5',
        title: 'Help!',
        year: 1965,
        imageUrl: 'assets/images/help.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 3,
        rare: false,
      },
      {
        id: '6',
        title: 'Rubber Soul',
        year: 1965,
        imageUrl: 'assets/images/rubber-soul.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 3,
        rare: false,
      },
      {
        id: '7',
        title: 'Revolver',
        year: 1966,
        imageUrl: 'assets/images/revolver.jpg',
        artist: { id: '1', name: 'The Beatles' },
        stock: 9,
        rare: true,
      },
    ],
  },
  {
    id: '2',
    name: 'The Rolling Stones',
    bio: 'The Rolling Stones are an English rock band formed in London in 1962. The first settled line-up consisted of Brian Jones, Ian Stewart, Mick Jagger, Keith Richards, Bill Wyman, and Charlie Watts.',
    imageUrl: 'assets/images/the-rolling-stones.jpg',
    albums: [
      {
        id: '8',
        title: 'The Rolling Stones',
        year: 1964,
        imageUrl: 'assets/images/rolling-stones.jpg',
        artist: { id: '2', name: 'The Rolling Stones' },
        stock: 5,
        rare: true,
      },
      {
        id: '9',
        title: 'The Rolling Stones No. 2',
        year: 1965,
        imageUrl: 'assets/images/rolling-stones-no-2.jpg',
        artist: { id: '2', name: 'The Rolling Stones' },
        stock: 2,
        rare: false,
      },
      {
        id: '10',
        title: 'Out of Our Heads',
        year: 1965,
        imageUrl: 'assets/images/out-of-our-heads.jpg',
        artist: { id: '2', name: 'The Rolling Stones' },
        stock: 20,
        rare: false,
      },
      {
        id: '11',
        title: 'Aftermath',
        year: 1966,
        imageUrl: 'assets/images/aftermath.jpg',
        artist: { id: '2', name: 'The Rolling Stones' },
        stock: 5,
        rare: false,
      },
      {
        id: '12',
        title: 'Between the Buttons',
        year: 1967,
        imageUrl: 'assets/images/between-the-buttons.jpg',
        artist: { id: '2', name: 'The Rolling Stones' },
        stock: 4,
        rare: false,
      },
    ],
  },
  {
    id: '3',
    name: 'The Beach Boys',
    bio: "A band formed in Hawthorne, California, in 1961. The group's original lineup consisted of brothers Brian, Dennis, and Carl Wilson, their cousin Mike Love, and their friend Al Jardine.",
    imageUrl: 'assets/images/the-beach-boys.jpg',
    albums: [
      {
        id: '13',
        title: "Surfin' Safari",
        year: 1962,
        imageUrl: 'assets/images/surfin-safari.jpg',
        artist: { id: '3', name: 'The Beachboys' },
        stock: 3,
        rare: false,
      },
      {
        id: '14',
        title: "Surfin' U.S.A.",
        year: 1963,
        imageUrl: 'assets/images/surfin-usa.jpg',
        artist: { id: '3', name: 'The Beachboys' },
        stock: 21,
        rare: false,
      },
      {
        id: '15',
        title: 'Pet Sounds',
        year: 1966,
        imageUrl: 'assets/images/pet-sounds.jpg',
        artist: { id: '3', name: 'The Beachboys' },
        stock: 1,
        rare: true,
      },
      {
        id: '16',
        title: 'Smiley Smile',
        year: 1967,
        imageUrl: 'assets/images/smiley-smile.jpg',
        artist: { id: '3', name: 'The Beachboys' },
        stock: 2,
        rare: false,
      },
    ],
  },
];
